#!/bin/bash
# GCE環境の手動セットアップ手順スクリプト
# プロジェクトオーナーまたは適切な権限を持つアカウントで実行してください

set -e

PROJECT_ID="bigquery-jukust"
REGION="asia-northeast1"
ZONE="asia-northeast1-a"
REPOSITORY="gsc-repo"
SERVICE_ACCOUNT="jukust-gcs@bigquery-jukust.iam.gserviceaccount.com"

echo "=========================================="
echo "GCE環境セットアップ手順"
echo "=========================================="
echo "プロジェクトID: $PROJECT_ID"
echo "サービスアカウント: $SERVICE_ACCOUNT"
echo ""
echo "以下の手順を実行してください："
echo ""

echo "1. 必要なAPIの有効化（プロジェクトオーナー権限が必要）"
echo "   gcloud services enable secretmanager.googleapis.com --project=$PROJECT_ID"
echo "   gcloud services enable artifactregistry.googleapis.com --project=$PROJECT_ID"
echo "   gcloud services enable compute.googleapis.com --project=$PROJECT_ID"
echo "   gcloud services enable cloudscheduler.googleapis.com --project=$PROJECT_ID"
echo ""

echo "2. Secret Managerへのシークレット登録"
echo "   # settings.ini を登録"
echo "   gcloud secrets create settings-ini \\"
echo "       --project=$PROJECT_ID \\"
echo "       --data-file=config/settings.ini \\"
echo "       --replication-policy=\"automatic\""
echo ""
echo "   # secrets.env を登録"
echo "   gcloud secrets create secrets-env \\"
echo "       --project=$PROJECT_ID \\"
echo "       --data-file=config/secrets.env \\"
echo "       --replication-policy=\"automatic\""
echo ""

echo "3. サービスアカウントへの権限付与"
echo "   # Secret Manager読み取り権限"
echo "   gcloud secrets add-iam-policy-binding settings-ini \\"
echo "       --member=\"serviceAccount:$SERVICE_ACCOUNT\" \\"
echo "       --role=\"roles/secretmanager.secretAccessor\" \\"
echo "       --project=$PROJECT_ID"
echo ""
echo "   gcloud secrets add-iam-policy-binding secrets-env \\"
echo "       --member=\"serviceAccount:$SERVICE_ACCOUNT\" \\"
echo "       --role=\"roles/secretmanager.secretAccessor\" \\"
echo "       --project=$PROJECT_ID"
echo ""
echo "   # Artifact Registry読み取り権限"
echo "   gcloud artifacts repositories add-iam-policy-binding $REPOSITORY \\"
echo "       --location=$REGION \\"
echo "       --member=\"serviceAccount:$SERVICE_ACCOUNT\" \\"
echo "       --role=\"roles/artifactregistry.reader\" \\"
echo "       --project=$PROJECT_ID"
echo ""

echo "4. Artifact Registryリポジトリの作成"
echo "   gcloud artifacts repositories create $REPOSITORY \\"
echo "       --repository-format=docker \\"
echo "       --location=$REGION \\"
echo "       --description=\"GSC Data Scraper Repository\" \\"
echo "       --project=$PROJECT_ID"
echo ""

echo "5. デプロイの実行（サービスアカウントで実行可能）"
echo "   export GOOGLE_CLOUD_PROJECT=$PROJECT_ID"
echo "   export GCE_REGION=$REGION"
echo "   export GCE_ZONE=$ZONE"
echo "   ./gce/deploy.sh"
echo ""

echo "=========================================="
echo "セットアップ完了後、上記の手順5でデプロイを実行してください"
echo "=========================================="

